services:
  odoo:
    build: .
    container_name: odoo
    command: python odoo-bin --config odoo.conf
    volumes:
      - ./odoo.conf:/opt/odoo/odoo.conf
    depends_on:
      - database
  database:
    image: postgres:17.4
    container_name: database
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo@homeserver
      - POSTGRES_DB=odoo-homerserver
    volumes:
      - /var/docker/volumes/postgres://var/lib/postgresql/data

    expose:
      - 5432
  server:
    build:
      context: config/
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - odoo
